AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Personal assistant for routine tasks

Parameters:
  SecretManagerExtension:
    Type: String
    Default: arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension:11
    Description: The secret manager extension ARN
  SpreadsheetId:
    Type: String
    Description: The spreadsheet contains user defined data
  TelegramChatId:
    Type: String
    Description: The chat should assistant send messages

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 512

Resources:
  GemLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: stellar-gems
      Description: The Stellar Assistant dependency
      ContentUri: .
      CompatibleRuntimes:
        - ruby3.2
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
  StellarApi:
    Type: AWS::Serverless::Function
    Name: "stellar-api"
    Metadata:
      BuildMethod: makefile
    Properties: &FunctionProperties
      Layers:
        - !Ref GemLayer
        - !Ref SecretManagerExtension
      Environment:
        Variables:
          HANAMI_ENV: production
          SPREADSHEET_ID: !Ref SpreadsheetId
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref StellarSecret
      CodeUri: .
      Handler: config/app.Hanami::Lambda.call
      Runtime: ruby3.2
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: StellarApiGateway
  StellarApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  StellarDailyJob:
    Type: AWS::Serverless::Function
    Name: "stellar-daily-job"
    Metadata:
      BuildMethod: makefile
    Properties:
      <<: *FunctionProperties
      Events:
        Scheduler:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: cron(0 9 * * ? *)
            ScheduleExpressionTimezone: Asia/Taipei
  StellarSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "stellar-secret"
