AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Personal assistant for routine tasks

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 512

Resources:
  StellarApiHandler:
    Type: AWS::Serverless::Function
    Name: "stellar-api"
    Properties:
      CodeUri: .
      Handler: config/lambda.Hanami::Lambda.call
      Runtime: ruby3.2
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: StellarApi
  StellarApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

Outputs:
  ApiEndpoint:
    Description: Stellar API endpoint
    Value: !Sub "https://${StellarApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
